name: Bug Report
description: Create a bug report for one of our services or bots.
title: "[Bug Report] Issue Description"
labels: [Bug]
assignees:
  - JakeyPrime
body:
  - type: checkboxes
    id: check
    attributes:
      label: Did You Search Other Issues?
      description: "Please search other issues FIRST, before continuing."
      options:
      - label: "I have checked other issues"
        required: true
  - type: textarea
    id: bug-description
    attributes:
      label: "Describe The Bug"
      description: "Please write a clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: "Reproduction Steps"
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "Please write a clear and concise description of what you expected to happen when doing or performing this action."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain and / or show your problem."
      render: bash
  - type: textarea
    id: other
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here, or leave blank."
