name: Bug Report
description: Create a bug report for one of our services or bots.
title: "[Bug Report] Title Goes Here"
labels: [Bug]
assignees:
  - JakeyPrime
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Please write a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Describe the bug
      description: Please write a clear and concise description of what you expected to happen when doing or performing this action.
    validations:
      required: true
  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain and / or show your problem.
  - type: textarea
    id: other
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, or leave blank.
