name: Feature Request
description: Suggest an idea for a Team Hydra service or project.
title: "[Feature Request] Title Goes Here"
labels: [Feature Request, User Suggestion]
assignees:
  - JakeyPrime
body:
  - type: checkboxes
    id: check
    attributes:
      label: "Did you search other suggestions?"
      description: "Please search other suggestions FIRST, before continuing."
      options:
      - label: "I have searched other suggestions"
        required: true
  - type: textarea
    id: feature-description
    attributes:
      label: "Is your feature request related to a problem?"
      description: "Please write a clear and concise description of what the problem is."
      placeholder: "I'm always frustrated when... (please use bug reports where appropriate)"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution, feature, or addon you'd like."
      description: "Please write a detailed description about how the feature will work, and be implemented."
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: "Why does the service need this?"
      description: "Please explain why this would enhance EVERYONE'S experience with using this service."
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Additional Context
      description: "Add any other context about the problem here, or leave blank."
